In [1]:
%pylab inline  

Populating the interactive namespace from numpy and matplotlib


Previous command loads numpy as np automatically

**Numpy** - math extension module for python. I is most used for fast vector, matrix and multi-dimensional array operations.

# Array initialization

In [4]:
X=array([[1,1],[2,2],[3,3]])
X

array([[1, 1],
       [2, 2],
       [3, 3]])

In [5]:
Y=array([11,12,13])
Y

array([11, 12, 13])

## Predefined arrays

In [7]:
zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [13]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arange(11,20)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
arange(11,20,2)

array([11, 13, 15, 17, 19])

linspace(start, stop, count) - make uniform grid, consisting of [count] points between [start] and [stop]

In [48]:
linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [49]:
linspace(0,10,6)

array([  0.,   2.,   4.,   6.,   8.,  10.])

In [50]:
linspace(0,10,3)

array([  0.,   5.,  10.])

Making logarithmic grid

In [54]:
10**linspace(-5,5,11)

array([  1.00000000e-05,   1.00000000e-04,   1.00000000e-03,
         1.00000000e-02,   1.00000000e-01,   1.00000000e+00,
         1.00000000e+01,   1.00000000e+02,   1.00000000e+03,
         1.00000000e+04,   1.00000000e+05])

In [153]:
# random array of shape=[2,3] with independent uniformly distributed elements from 0 to 1
random.uniform(0,1,[2,3])  

array([[ 0.28971758,  0.46448745,  0.90837075],
       [ 0.04675528,  0.09018255,  0.15358742]])

In [154]:
# random array of shape=[2,3] with independent elements with Gaussian distribution with mean 0 and variance 1
random.normal(0,1,[2,3])  

array([[-2.29507214,  1.89613598,  0.54735087],
       [-0.66422802,  0.51489803,  1.57719273]])

# Mathematic operations

In [269]:
A=array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Operations on single array

In [268]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [186]:
A+10

array([[11, 12, 13],
       [13, 14, 15],
       [17, 18, 19]])

In [190]:
10*A

array([[10, 20, 30],
       [30, 40, 50],
       [70, 80, 90]])

In [187]:
A%2

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]], dtype=int32)

In [188]:
A**2

array([[ 1,  4,  9],
       [ 9, 16, 25],
       [49, 64, 81]])

In [189]:
2**A

array([[  2,   4,   8],
       [  8,  16,  32],
       [128, 256, 512]], dtype=int32)

In [231]:
sqrt(A)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712],
       [ 3.        ,  3.16227766,  3.31662479,  3.46410162],
       [ 3.60555128,  3.74165739,  3.87298335,  4.        ]])

In [232]:
sin(A)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292],
       [ 0.42016704,  0.99060736,  0.65028784, -0.28790332]])

### sum

In [59]:
A.sum()  # sum of all elements

45

after *pylab inline* command built-in *sum* function was replaced with numpy *sum*

In [78]:
np.sum(A)

45

In [68]:
A.sum(0)   # sum along 0-th axis  (along rows)

array([12, 15, 18])

In [79]:
sum(A,0)   # sum along 0-th axis  (along rows)

array([12, 15, 18])

In [80]:
A.sum(1)   # sum along 1-st axis (along columns) 

array([ 6, 15, 24])

In [81]:
sum(A,1)   # sum along 1-st axis (along columns) 

array([ 6, 15, 24])

In [72]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### mean

In [ ]:
mean calculates the average value

In [270]:
A.mean()

5.0

In [271]:
A.mean(0)

array([ 4.,  5.,  6.])

In [272]:
A.mean(1)

array([ 2.,  5.,  8.])

### max

In [82]:
A.max()  # maximum over all elements

9

In [83]:
np.max(A)   # maximum over all elements

9

In [84]:
A.max(0)  # maximum along 0-th axis (along rows), so we get column-wise maximums

array([7, 8, 9])

In [85]:
np.max(A,0)   # maximum along 0-th axis (along rows), so we get column-wise maximums

array([7, 8, 9])

In [87]:
A.max(1)   # maximum along 1-st axis (along columns), so we get row-wise maximums

array([3, 6, 9])

In [88]:
np.max(A,1)    # maximum along 1-st axis (along columns), so we get row-wise maximums

array([3, 6, 9])

min functon works analogous to max

### maximum

In [104]:
A=[1,20,3,40]
B=[10,2,30,4]

In [102]:
np.maximum(A,B)   # elementwise maximum

array([10, 20, 30, 40])

minimum functon works analogous to maximum

## Operations on two arrays

In [27]:
A=array([[1,2],[3,4]])
B=array([[10,0],[0,10]])

In [28]:
A

array([[1, 2],
       [3, 4]])

In [29]:
B

array([[10,  0],
       [ 0, 10]])

In [30]:
A+B

array([[11,  2],
       [ 3, 14]])

In [31]:
A-B

array([[-9,  2],
       [ 3, -6]])

In [32]:
A*B  # elemenstwise!

array([[10,  0],
       [ 0, 40]])

In [33]:
np.dot(A,B) # matrix multiplication

array([[10, 20],
       [30, 40]])

# shape

Gives the number of dimensions for the array and dimensionality along each dimension

In [38]:
A=array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
A.shape # dimensions of array A

(2, 3)

In [40]:
len(A)  # dimensionality along the first dimension

2

# Iteration

In [41]:
for elem in A:
    print(elem)

[1 2 3]
[4 5 6]


# newaxis

In [108]:
A=array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [109]:
A.shape  # one dimension

(5,)

### Vector-row

In [110]:
A[newaxis,:]

array([[1, 2, 3, 4, 5]])

### Vector-column

In [111]:
A[:,newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

# Boolean operations

In [114]:
A=arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
A>4

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [117]:
A<7

array([ True,  True,  True,  True,  True,  True,  True, False, False, False], dtype=bool)

In [118]:
any(A>4)

True

In [119]:
any(A>10)

False

In [120]:
all(A<10)

True

In [122]:
(A>4) & (A<7)

array([False, False, False, False, False,  True,  True, False, False, False], dtype=bool)

# reshape

In [178]:
A=arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [180]:
A.reshape([3,4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [181]:
A.reshape([4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [182]:
A.reshape([2,6])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

# ravel

In [183]:
A=array([[1,2,3],[3,4,5],[7,8,9]])
A

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [184]:
A.ravel()

array([1, 2, 3, 3, 4, 5, 7, 8, 9])

# Boolean operations

In [251]:
A=arange(10,20)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [252]:
A==12

array([False, False,  True, False, False, False, False, False, False, False], dtype=bool)

In [253]:
A!=12

array([ True,  True, False,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [254]:
A>12

array([False, False, False,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [255]:
any([True,True,False])

True

In [256]:
all([True,True,False])

False

In [259]:
A=arange(9).reshape([3,3])
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [260]:
A>4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [265]:
any(A>4,0)  # any along 0 dimension (rows)

array([ True,  True,  True], dtype=bool)

In [264]:
any(A>4,1)  # any along 1 dimension (columns)

array([False,  True,  True], dtype=bool)

In [266]:
all(A>4,0)  # all along 0 dimension (rows)

array([False, False, False], dtype=bool)

In [267]:
all(A>4,1)  # all along 1 dimension (columns)

array([False, False,  True], dtype=bool)

# Indexing

### Boolean indexing

In [124]:
A=arange(10,20)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [125]:
A[A>13]

array([14, 15, 16, 17, 18, 19])

In [126]:
A[A<18]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [127]:
A[(A>13) & (A<18)]

array([14, 15, 16, 17])

### Integer indexing

In [129]:
inds = [0,2,4,6,8]
A[inds]

array([10, 12, 14, 16, 18])

### Convert boolean indexes to integer indexes

In [138]:
sels = A>13
sels

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [139]:
inds = find(sels)
inds

array([4, 5, 6, 7, 8, 9], dtype=int64)

In [140]:
A[sels]

array([14, 15, 16, 17, 18, 19])

In [141]:
A[inds]

array([14, 15, 16, 17, 18, 19])

### Convert integer indexes to boolean indexes

In [142]:
sels = zeros(len(A), dtype=bool)
sels

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [143]:
inds=[0,2,4,6,8]

In [145]:
sels[inds]=True
sels

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [148]:
A[inds]

array([10, 12, 14, 16, 18])

In [149]:
A[sels]

array([10, 12, 14, 16, 18])

### Random selection

Select randomly 3 elements

In [157]:
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [158]:
L=arange(len(A))
random.shuffle(L)  # random reordering of sequence, in-place
L

array([3, 0, 8, 2, 9, 1, 4, 6, 5, 7])

In [159]:
inds = L[:3]
inds

array([3, 0, 8])

Select each element with probability 0.1

In [162]:
u = random.uniform(0,1,A.shape)
u

array([ 0.89309343,  0.88468399,  0.55584205,  0.29130004,  0.44921448,
        0.51058224,  0.2824664 ,  0.05699617,  0.51528102,  0.04434267])

In [163]:
u<0.1

array([False, False, False, False, False, False, False,  True, False,  True], dtype=bool)

In [165]:
find(u<0.1)

array([7, 9], dtype=int64)

# Slicing

In [222]:
A=arange(1,16+1).reshape([4,4])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [223]:
A[:]  # copy of array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [225]:
A[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [226]:
A[:-2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [227]:
A[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [228]:
A[:,:-2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [229]:
A[2:,2:]

array([[11, 12],
       [15, 16]])

In [230]:
A[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

# Broadcasting

In [166]:
A=array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
B=array([10,20])[:,newaxis]
B

array([[10],
       [20]])

In [170]:
A+B

array([[11, 12, 13],
       [24, 25, 26]])

In [173]:
C=array([100,200,300])[newaxis,:]
C

array([[100, 200, 300]])

In [174]:
A+C

array([[101, 202, 303],
       [104, 205, 306]])

In [175]:
A+1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006]])

# sorting

### Sorting vectors

In [247]:
a = array([1,2,3,4,3,2,1])
a

array([1, 2, 3, 4, 3, 2, 1])

In [248]:
sort(a)  # returns sorted array, not in-place

array([1, 1, 2, 2, 3, 3, 4])

In [249]:
inds = argsort(a)  # return indexes which sort the array
a[inds]

array([1, 1, 2, 2, 3, 3, 4])

### Sorting matrices

In [217]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A

array([[ 40,  30,  20,  10],
       [  1,   2,   3,   4],
       [300, 400, 100, 200]])

In [213]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A.sort(0)  # sorts along 0-th dimension (along rows), returns sorted columns, in-place
A

array([[  1,   2,   3,   4],
       [ 40,  30,  20,  10],
       [300, 400, 100, 200]])

In [215]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A.sort(1)  # sorts along 1-st dimension (along rows), returns sorted columns, in-place
A

array([[ 10,  20,  30,  40],
       [  1,   2,   3,   4],
       [100, 200, 300, 400]])

Get indexes which make the array sorted

In [218]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
argsort(A,0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)

In [219]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
argsort(A,1)

array([[3, 2, 1, 0],
       [0, 1, 2, 3],
       [2, 3, 0, 1]], dtype=int64)

Multidimensional arrays also may be sorted along any dimension

# Unique elements

In [235]:
A = [0,1,1,2,2,2,3,3,3,3,3,3,3]
A

[0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3]

In [236]:
u = unique(A)
u

array([0, 1, 2, 3])

In [237]:
unique(A, return_counts=True)

(array([0, 1, 2, 3]), array([1, 2, 3, 7], dtype=int64))

In [274]:
a=arange(-3,3)
a

array([-3, -2, -1,  0,  1,  2])

# Saving memory

In [309]:
A=eye(100)

In [310]:
A.dtype, A.nbytes

(dtype('float64'), 80000)

In [311]:
A=A.astype(float32)

In [312]:
A.dtype, A.nbytes  # two times less memory usage!

(dtype('float32'), 40000)

### Sparse matrices

Store only non-zero entries of a matrix. Efficient when the majority of elements are zeroes.

In [313]:
A

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]], dtype=float32)

In [314]:
import scipy
from scipy import sparse
A =  scipy.sparse.dok_matrix(A)

In [316]:
A.dtype, A.nnz*4  # effective size is zero, because it stores only non-zero elements

(dtype('float32'), 400)

# Special values

### nan

nan stands for "not a number". Its value is undefined, and it can mean any number.

In [276]:
0/0

ZeroDivisionError: division by zero

In [279]:
float64(0)/float64(0)

C:\Development\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':


nan

In [277]:
float32(0)/float32(0)

C:\Development\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in float_scalars
  if __name__ == '__main__':


nan

In [317]:
1/0

ZeroDivisionError: division by zero

In [318]:
float32(1)/float32(0)

C:\Development\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in float_scalars
  if __name__ == '__main__':


inf

In [319]:
float32(-1)/float32(0)

C:\Development\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in float_scalars
  if __name__ == '__main__':


-inf

In [321]:
isfinite([1,inf,-inf,nan])

array([ True, False, False, False], dtype=bool)

In [322]:
isinf([1,inf,-inf,nan])

array([False,  True,  True, False], dtype=bool)

In [323]:
isnan([1,inf,-inf,nan])

array([False, False, False,  True], dtype=bool)

## max, argmax

In [326]:
a=array([11,12,13,12,11])
a

array([11, 12, 13, 12, 11])

In [327]:
max(a) # built-in python function, finds max for any iterable

13

In [330]:
ind = argmax(a)  # returns index of the maximum value
a[ind]

13

In [331]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A

array([[ 40,  30,  20,  10],
       [  1,   2,   3,   4],
       [300, 400, 100, 200]])

In [332]:
A.max() # find global max

400

In [333]:
A.max(0) # max along 0-th dimension (rows)

array([300, 400, 100, 200])

In [ ]:
np.max(A,0)  # equivalent to A.max(0)

In [336]:
A.max(1) # max along 1-st dimension (columns)

array([ 40,   4, 400])

In [337]:
np.max(A,1)  # equivalent to A.max(1)

array([ 40,   4, 400])

Learn more:
* [Tutorial on numpy/scipy](http://www.scipy-lectures.org/)
* [Function optimization in scipy](http://www.scipy-lectures.org/advanced/mathematical_optimization/index.html)