# Numpy demo

#### Demo, showing major numpy module functionality.

#### Author: Victor Kitov (v.v.kitov@yandex.ru)

In [1]:
%pylab inline  

Populating the interactive namespace from numpy and matplotlib


Previous command loads numpy as np automatically

**Numpy** - math extension module for python. I is most used for fast vector, matrix and multi-dimensional array operations.

In [2]:
L=[True,1,1/3,'hello']

In [3]:
L

[True, 1, 0.3333333333333333, 'hello']

# Array initialization

In [13]:
X=array([[1,1],[2,2],[3,3]],dtype=float)
X

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

In [14]:
X.dtype

dtype('float64')

In [15]:
X[0,0]=1/3

In [16]:
X[0,0]

0.33333333333333331

In [17]:
Y=array([11,12,13])
Y

array([11, 12, 13])

## Predefined arrays

In [23]:
zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [24]:
ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [25]:
eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arange(11,20)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
arange(11,20,2)

array([11, 13, 15, 17, 19])

linspace(start, stop, count) - make uniform grid, consisting of [count] points between [start] and [stop]

In [32]:
linspace(-5,5,11)

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [31]:
linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [ ]:
linspace(0,10,6)

In [ ]:
linspace(0,10,3)

Making logarithmic grid

In [6]:
10**linspace(-3,3,7)

array([  1.00000000e-03,   1.00000000e-02,   1.00000000e-01,
         1.00000000e+00,   1.00000000e+01,   1.00000000e+02,
         1.00000000e+03])

In [5]:
logspace(-3,3,7)

array([  1.00000000e-03,   1.00000000e-02,   1.00000000e-01,
         1.00000000e+00,   1.00000000e+01,   1.00000000e+02,
         1.00000000e+03])

In [ ]:
# random array of shape=[2,3] with independent uniformly distributed elements from 0 to 1
random.uniform(0,1,[2,3])  

In [ ]:
# random array of shape=[2,3] with independent elements with Gaussian distribution with mean 0 and variance 1
random.normal(0,1,[2,3])  

# Mathematic operations

In [8]:
A=array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Operations on single array

In [42]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
A+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [37]:
10*A

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [38]:
A%2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [39]:
A**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [40]:
2**A

array([[  2,   4,   8],
       [ 16,  32,  64],
       [128, 256, 512]], dtype=int32)

In [45]:
sqrt(A)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974],
       [ 2.64575131,  2.82842712,  3.        ]])

In [46]:
sin(A)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

### sum

In [9]:
A.sum()  # sum of all elements

45

after *pylab inline* command built-in *sum* function was replaced with numpy *sum*

In [11]:
np.sum(A)

45

In [10]:
sum(A)

45

In [49]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
A.sum(0)   # sum along 0-th axis  (along rows)

array([12, 15, 18])

In [13]:
sum(A,0)   # sum along 0-th axis  (along rows)

array([12, 15, 18])

In [15]:
A.sum(1)   # sum along 1-st axis (along columns) 

array([ 6, 15, 24])

In [16]:
sum(A,1)   # sum along 1-st axis (along columns) 

array([ 6, 15, 24])

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### mean

mean calculates the average value

In [19]:
A.mean()

5.0

In [20]:
A.mean(0)

array([ 4.,  5.,  6.])

In [21]:
A.mean(1)

array([ 2.,  5.,  8.])

### max

In [54]:
A.max()  # maximum over all elements

9

In [55]:
np.max(A)   # maximum over all elements

9

In [56]:
A.max(0)  # maximum along 0-th axis (along rows), so we get column-wise maximums

array([7, 8, 9])

In [ ]:
np.max(A,0)   # maximum along 0-th axis (along rows), so we get column-wise maximums

In [57]:
A.max(1)   # maximum along 1-st axis (along columns), so we get row-wise maximums

array([3, 6, 9])

In [ ]:
np.max(A,axis=1)    # maximum along 1-st axis (along columns), so we get row-wise maximums

min functon works analogous to max

### maximum

In [58]:
A=[1,20,3,40]
B=[10,2,30,4]

In [59]:
np.maximum(A,B)   # elementwise maximum

array([10, 20, 30, 40])

minimum functon works analogous to maximum

## Operations on two arrays

In [60]:
A=array([[1,2],[3,4]])
B=array([[10,0],[0,10]])

In [61]:
A

array([[1, 2],
       [3, 4]])

In [62]:
B

array([[10,  0],
       [ 0, 10]])

In [63]:
A+B

array([[11,  2],
       [ 3, 14]])

In [64]:
A-B

array([[-9,  2],
       [ 3, -6]])

In [65]:
A*B  # elemenstwise!

array([[10,  0],
       [ 0, 40]])

In [66]:
np.dot(A,B) # matrix multiplication

array([[10, 20],
       [30, 40]])

# shape

Gives the number of dimensions for the array and dimensionality along each dimension

In [67]:
A=array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
A.shape # dimensions of array A

(2, 3)

In [69]:
len(A)  

2

# Iteration

In [ ]:
for elem in A:
    print(elem)

# newaxis

In [ ]:
A=array([1,2,3,4,5])
A

In [ ]:
A.shape  # one dimension

### Vector-row

In [ ]:
A[newaxis,:]

### Vector-column

In [ ]:
A[:,newaxis]

# Boolean operations

In [ ]:
A=arange(10)
A

In [ ]:
A>4

In [ ]:
A<7

In [ ]:
any(A>4)

In [ ]:
any(A>10)

In [ ]:
all(A<10)

In [ ]:
(A>4) & (A<7)

# reshape

In [ ]:
A=arange(12)
A

In [ ]:
A.reshape([3,4])

In [ ]:
A.reshape([4,3])

In [ ]:
A.reshape([2,6])

# ravel

In [ ]:
A=array([[1,2,3],[3,4,5],[7,8,9]])
A

In [ ]:
A.ravel()

# Boolean operations

In [ ]:
A=arange(10,20)
A

In [ ]:
A==12

In [ ]:
A!=12

In [ ]:
A>12

In [ ]:
any([True,True,False])

In [ ]:
all([True,True,False])

In [ ]:
A=arange(9).reshape([3,3])
A

In [ ]:
A>4

In [ ]:
any(A>4,0)  # any along 0 dimension (rows)

In [ ]:
any(A>4,1)  # any along 1 dimension (columns)

In [ ]:
all(A>4,0)  # all along 0 dimension (rows)

In [ ]:
all(A>4,1)  # all along 1 dimension (columns)

# Indexing

### Boolean indexing

In [ ]:
A=arange(10,20)
A

In [ ]:
A[[2,3,4]]

In [ ]:
A[A>13]

In [ ]:
A[A<18]

In [ ]:
A[(A>13) & (A<18)]

### Integer indexing

In [ ]:
inds = [0,2,4,6,8]
A[inds]

### Convert boolean indexes to integer indexes

In [ ]:
sels = A>13
sels

In [ ]:
inds = find(sels)
inds

In [ ]:
A[sels]

In [ ]:
A[inds]

### Convert integer indexes to boolean indexes

In [ ]:
sels = zeros(len(A), dtype=bool)
sels

In [ ]:
inds=[0,2,4,6,8]

In [ ]:
sels[inds]=True
sels

In [ ]:
A[inds]

In [ ]:
A[sels]

### Random selection

Select randomly 3 elements

In [ ]:
A

In [ ]:
L=arange(len(A))
random.shuffle(L)  # random reordering of sequence, in-place
L

In [ ]:
inds = L[:3]
inds

Select each element with probability 0.1

In [ ]:
u = random.uniform(0,1,A.shape)
u

In [ ]:
u<0.1

In [ ]:
find(u<0.1)

# Slicing

In [ ]:
A=arange(1,16+1).reshape([4,4])
A

In [ ]:
A[:]  # copy of array

In [ ]:
A[2:]

In [ ]:
A[:-2]

In [ ]:
A[:,2:]

In [ ]:
A[:,:-2]

In [ ]:
A[2:,2:]

In [ ]:
A[::2,::2]

# Broadcasting

In [ ]:
A=array([[1,2,3],[4,5,6]])
A

In [ ]:
B=array([10,20])[:,newaxis]
B

In [ ]:
A+B

In [ ]:
C=array([100,200,300])[newaxis,:]
C

In [ ]:
A+C

In [ ]:
A+1000

# sorting

### Sorting vectors

In [ ]:
a = array([1,2,3,4,3,2,1])
a

In [ ]:
sort(a)  # returns sorted array, not in-place

In [ ]:
inds = argsort(a)  # return indexes which sort the array
a[inds]

### Sorting matrices

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A.sort(0)  # sorts along 0-th dimension (along rows), returns sorted columns, in-place
A

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A.sort(1)  # sorts along 1-st dimension (along rows), returns sorted columns, in-place
A

Get indexes which make the array sorted

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
argsort(A,0)

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
argsort(A,1)

Multidimensional arrays also may be sorted along any dimension

# Unique elements

In [ ]:
A = [0,1,1,2,2,2,3,3,3,3,3,3,3]
A

In [ ]:
u = unique(A)
u

In [ ]:
unique(A, return_counts=True)

In [ ]:
a=arange(-3,3)
a

# Saving memory

In [ ]:
A=eye(100)

In [ ]:
A.dtype, A.nbytes

In [ ]:
A=A.astype(float32)

In [ ]:
A.dtype, A.nbytes  # two times less memory usage!

In [ ]:
A.dtype

### Sparse matrices

Store only non-zero entries of a matrix. Efficient when the majority of elements are zeroes.

In [ ]:
A

In [ ]:
import scipy
from scipy import sparse
A =  scipy.sparse.dok_matrix(A)

In [ ]:
A.dtype, A.nnz*4  # effective size is zero, because it stores only non-zero elements

# Special values

### nan

nan stands for "not a number". Its value is undefined, and it can mean any number.

In [ ]:
0/0

In [ ]:
float64(0)/float64(0)

In [ ]:
float32(0)/float32(0)

In [ ]:
1/0

In [ ]:
float32(1)/float32(0)

In [ ]:
float32(-1)/float32(0)

In [ ]:
isfinite([1,inf,-inf,nan])

In [ ]:
isinf([1,inf,-inf,nan])

In [ ]:
isnan([1,inf,-inf,nan])

## max, argmax

In [ ]:
a=array([11,12,13,12,11])
a

In [ ]:
max(a) # built-in python function, finds max for any iterable

In [ ]:
ind = argmax(a)  # returns index of the maximum value
a[ind]

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A

In [ ]:
A.max() # find global max

In [ ]:
A.max(0) # max along 0-th dimension (rows)

In [ ]:
np.max(A,0)  # equivalent to A.max(0)

In [ ]:
A.max(1) # max along 1-st dimension (columns)

In [ ]:
np.max(A,1)  # equivalent to A.max(1)

Learn more:
* [Tutorial on numpy/scipy](http://www.scipy-lectures.org/)
* [Function optimization in scipy](http://www.scipy-lectures.org/advanced/mathematical_optimization/index.html)